# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimg', models.CharField(max_length=200)),
                ('btype', models.CharField(max_length=200)),
                ('bname', models.CharField(max_length=200)),
                ('bservices', models.CharField(max_length=400)),
                ('bphoneno', models.IntegerField(max_length=15)),
                ('baddress', models.CharField(max_length=150)),
                ('bowner', models.CharField(max_length=200, null=True)),
                ('bemail', models.CharField(max_length=200, null=True)),
                ('bwebsite', models.CharField(max_length=200, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=3000)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoj.Post')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoj.User'),
        ),
    ]
